/**
 * Mapping fichier de commande → métadonnées
 * Utilisé par !aide nouveautes et !aidestaff nouveautes pour afficher
 * les commandes les plus récemment modifiées.
 *
 * staff: true  → commande réservée au staff (non affichée dans !aide)
 * staff: false → commande publique
 * staff: 'mixed' → contient des sous-commandes publiques ET staff
 */
module.exports = {
  'absence.js':        { commands: ['!absence declarer [raison]', '!absence annuler', '!absence liste <équipe>'],                              staff: 'mixed' },
  'achievement.js':    { commands: ['!trophee <icône> <équipe>', '!trophees <équipe>', '!mvpsaison'],                                          staff: 'mixed' },
  'addmatch.js':       { commands: ['!ajoutermatch <équipe> <placement> <kills>'],                                                             staff: true },
  'adminlogs.js':      { commands: ['!journauxadmin', '!jadmin'],                                                                             staff: true },
  'afk.js':            { commands: ['!absent [message]'],                                                                                     staff: false },
  'aide.js':           { commands: ['!aide', '!aide historique', '!aide nouveautes', '!chercher <terme>'],                                    staff: false },
  'aidestaff.js':      { commands: ['!aidestaff', '!aidestaff historique', '!aidestaff nouveautes', '!chercher staff <terme>'],               staff: true },
  'alerteperf.js':     { commands: ['!alerteperf <équipe> <seuil> #salon'],                                                                   staff: true },
  'announce.js':       { commands: ['!annonce <message>'],                                                                                    staff: true },
  'antispam.js':       { commands: ['!antispam activer|desactiver|configurer'],                                                               staff: true },
  'automod.js':        { commands: ['!automod activer|desactiver|statut|test', '!mots ajouter|retirer|defaut|vider'],                         staff: true },
  'autorole.js':       { commands: ['!rolesauto definir @role|activer|desactiver'],                                                           staff: true },
  'backup.js':         { commands: ['!sauvegarde creer|liste|info|supprimer', '!restaurer'],                                                  staff: true },
  'birthday.js':       { commands: ['!anniversaire definir|supprimer|liste|prochains|verifier', '!salonanniversaires #salon'],                staff: 'mixed' },
  'blacklist.js':      { commands: ['!listenoiree ajouter|retirer|liste|verifier'],                                                           staff: 'mixed' },
  'botstats.js':       { commands: ['!statsbot'],                                                                                             staff: true },
  'bracket.js':        { commands: ['!tableau [T1,T2,…]'],                                                                                   staff: false },
  'changelog.js':      { commands: ['!journal [N]', '!misesajour [N]'],                                                                      staff: true },
  'commandes.js':      { commands: ['!commandes'],                                                                                            staff: false },
  'compare.js':        { commands: ['!comparer <T1> vs <T2>'],                                                                               staff: false },
  'configbot.js':      { commands: ['!config', '!definitpoints <placement>'],                                                                 staff: 'mixed' },
  'cooldowncmd.js':    { commands: ['!delais', '!configdelai <commande> <sec>', '!supprimerdelai <commande>'],                               staff: true },
  'dashboard.js':      { commands: ['!tableaudebord', '!tableaudebord lien', '!tableaudebord salon|auto|heure|statut'],                      staff: 'mixed' },
  'deletetournoi.js':  { commands: ['!supprimertournoi <nom>'],                                                                               staff: true },
  'diffuser.js':       { commands: ['!diffuser <message>|ajouter|retirer|liste|aperçu'],                                                     staff: true },
  'dispo.js':          { commands: ['!dispo oui|non|incertain', '!dispo match|voir|effacer|liste'],                                          staff: 'mixed' },
  'embed.js':          { commands: ['!embed simple|boutons|riche|complet|liste|modifier|supprimer|cloner|programmer|programmes|déprogrammer|modèle'], staff: true },
  'embedbuilder.js':   { commands: ['!embedplus'],                                                                                            staff: true },
  'endtournoi.js':     { commands: ['!finirtournoi'],                                                                                         staff: true },
  'equipesplus.js':    { commands: ['!equipes', '!agentslibres', '!transfert', '!capitaine <équipe>', '!comparerjoueur <J1> | <J2>'],         staff: 'mixed' },
  'erreurs.js':        { commands: ['!erreurs', '!erreurs nonresolues|stats|resoudre|vider'],                                                 staff: true },
  'eventcmd.js':       { commands: ['!evenement creer|liste|joindre|quitter|participants|annuler'],                                          staff: 'mixed' },
  'export.js':         { commands: ['!exporter [json|csv|texte]'],                                                                            staff: true },
  'formrecente.js':    { commands: ['!formrecente <équipe> [N]'],                                                                             staff: false },
  'gelerclassement.js':{ commands: ['!gelerclassement', '!degerlerclassement', '!synchroniserrangs'],                                        staff: true },
  'gitpush.js':        { commands: ['!envoyergit'],                                                                                           staff: true },
  'gitstatus.js':      { commands: ['!statutgit'],                                                                                            staff: true },
  'giveaway.js':       { commands: ['!concours <durée> <prix>', '!retirer <messageId>'],                                                      staff: true },
  'history.js':        { commands: ['!historique <équipe>'],                                                                                  staff: false },
  'ia.js':             { commands: ['!ia <question>', '!ia analyser|predire|conseil|resume|rapport|entrainement|strategie|bilan|depistage|debrief|historique|reinitialiser|modeles|modele|statistiques|quota|basculement'], staff: 'mixed' },
  'inscription.js':    { commands: ['!inscription ouvrir|fermer|liste|valider|refuser|max|salon|annonces|reinitialiser'],                    staff: true },
  'inscrire.js':       { commands: ['!inscrire <équipe> | <J1,J2,…>'],                                                                       staff: false },
  'level.js':          { commands: ['!niveau [@membre]', '!classniveau', '!classxp', '!salonniveaux #salon'],                                staff: 'mixed' },
  'lien.js':           { commands: ['!lienbot'],                                                                                              staff: false },
  'lineup.js':         { commands: ['!composition <équipe>', '!composition definir|effacer|liste'],                                          staff: 'mixed' },
  'lockdown.js':       { commands: ['!verrouiller', '!deverrouiller'],                                                                        staff: true },
  'loghistory.js':     { commands: ['!journaux', '!journaux statistiques|aujourdhui|vider'],                                                  staff: true },
  'logosubmit.js':     { commands: ['%logo <équipe>'],                                                                                        staff: false },
  'maintenance.js':    { commands: ['!maintenance activer|desactiver|message|statut'],                                                        staff: true },
  'matchs.js':         { commands: ['!matchs'],                                                                                               staff: false },
  'moderation.js':     { commands: ['!effacer <N>', '!lenteur <sec>', '!mp @membre <message>', '!sourdine @membre <durée>', '!retablir @membre'], staff: true },
  'moderationplus.js': { commands: ['!casier @membre', '!rapport', '!topavertissements'],                                                     staff: true },
  'motd.js':           { commands: ['!messagejour', '!configmdj <texte>'],                                                                   staff: 'mixed' },
  'mvp.js':            { commands: ['!mvp'],                                                                                                   staff: false },
  'mvpseason.js':      { commands: ['!mvpsaison'],                                                                                            staff: false },
  'newsletter.js':     { commands: ['!infolettre salon|activer|desactiver|tester|statut'],                                                   staff: true },
  'newtournoi.js':     { commands: ['!nouveautournoi <nom>'],                                                                                 staff: true },
  'note.js':           { commands: ['!note <équipe> <texte>', '!notes <équipe>', '!supprimenote <id>'],                                       staff: true },
  'notifequipe.js':    { commands: ['!notifequipe <équipe> | <message>'],                                                                     staff: true },
  'objectif.js':       { commands: ['!objectif voir|progression|definir|supprimer|liste'],                                                   staff: 'mixed' },
  'ping.js':           { commands: ['!ping'],                                                                                                  staff: false },
  'planifier.js':      { commands: ['!planifier creer|liste|voir|modifier|supprimer|pause|dupliquer|tester'],                                staff: true },
  'playerstats.js':    { commands: ['!statsjoueur <nom>', '!classjoueurs', '!matchjoueur <équipe> <joueur> <kills>', '!reinitjoueur <équipe> <nom>'], staff: 'mixed' },
  'poll.js':           { commands: ['!vote <question>', '!sondage <durée> <question> | <opt…>', '!sondage programmer|planifie'],             staff: 'mixed' },
  'poule.js':          { commands: ['!poule creer|classement|resultat|liste|supprimer'],                                                      staff: 'mixed' },
  'profil.js':         { commands: ['!profil [@membre]'],                                                                                     staff: false },
  'pronostic.js':      { commands: ['!pronostic <T1> vs <T2>', '!pronostic resultats|classement|valider'],                                   staff: 'mixed' },
  'random.js':         { commands: ['!pileface', '!tirageequipe [T1,T2,…]'],                                                                  staff: false },
  'ranking.js':        { commands: ['!classement', '!classement eliminations|ratio|<tournoi>'],                                              staff: false },
  'rankroles.js':      { commands: ['!definitrecompense <rang> @role', '!supprimerrecompense <rang>', '!recompenses', '!lierequipe <équipe> @role'], staff: 'mixed' },
  'rapportHebdo.js':   { commands: ['!rapporthebdo salon|activer|desactiver|tester|statut'],                                                 staff: true },
  'reactionrole.js':   { commands: ['!rolereaction ajouter|retirer|vider|liste'],                                                            staff: true },
  'recap.js':          { commands: ['!recapitulatif [nom_tournoi]'],                                                                            staff: false },
  'register.js':       { commands: ['!enregistrer <nom>', '!desenregistrer <nom>', '!renommer <ancien> | <nouveau>'],                        staff: true },
  'reglementcmd.js':   { commands: ['!reglement', '!reglement titre|intro|section|ajouter|modifier|supprimer|publier|actualiser|reinitialiser', '!ajouterregle|modifierregle|supprimerregle|deplacerregle|effacerregles'], staff: 'mixed' },
  'remind.js':         { commands: ['!rappel <durée> <texte>'],                                                                               staff: false },
  'repertoire.js':     { commands: ['!repertoire'],                                                                                           staff: false },
  'report.js':         { commands: ['!signaler <problème>'],                                                                                  staff: false },
  'resetmatch.js':     { commands: ['!annulermatch <id>', '!reinitialiser'],                                                                  staff: true },
  'result.js':         { commands: ['!resultats salon|statut|depuis'],                                                                        staff: true },
  'roleinfo.js':       { commands: ['!inforole @role'],                                                                                       staff: false },
  'roster.js':         { commands: ['!liste <équipe>', '!liste ajouter|retirer|role|note|vider|capitaine'],                                  staff: 'mixed' },
  'rules.js':          { commands: ['!regles', '!definirregles <titre> | <règle1> | ...'],                                                    staff: 'mixed' },
  'sanctions.js':      { commands: ['!sanctions [@membre]', '!avertissements [@membre]', '!punition @membre <type>', '!effaceractions @membre'], staff: 'mixed' },
  'say.js':            { commands: ['!dire [#salon] <texte>'],                                                                                staff: true },
  'schedule.js':       { commands: ['!calendrier', '!calendrier prochain|equipe|salon|rappel|statut|ajouter|modifier|supprimer|vider'],      staff: 'mixed' },
  'scout.js':          { commands: ['!depistage <joueur>', '!depistage comparer <J1> vs <J2>'],                                             staff: false },
  'search.js':         { commands: ['!recherche <nom>'],                                                                                      staff: false },
  'season.js':         { commands: ['!saisons', '!palmares', '!nouvellesaison <nom>', '!finersaison', '!classementsaison <nom>'],            staff: 'mixed' },
  'serverinfo.js':     { commands: ['!infoserveur'],                                                                                          staff: false },
  'setchannel.js':     { commands: ['!salonannonce', '!salonjournaux', '!salonsoumissionlogos', '!salonaffichagelogos'],                     staff: true },
  'setlogo.js':        { commands: ['!configlogo <équipe> | <url>'],                                                                          staff: true },
  'sondage.js':        { commands: ['!sondage historique|stats'],                                                                            staff: false },
  'stats_advanced.js': { commands: ['!serie <équipe>', '!regularite <équipe>', '!faceatface <T1> <T2>', '!calculer <placement> <kills>', '!vainqueurs'], staff: false },
  'stats.js':          { commands: ['!statistiques <équipe>', '!infoequipe <nom>', '!top [N]'],                                              staff: false },
  'statsplus.js':      { commands: ['!moyenne <équipe>', '!tendance <équipe>', '!meilleurmatch <équipe>', '!pirematch <équipe>', '!podium', '!resume', '!prediction <T1> vs <T2>'], staff: false },
  'status.js':         { commands: ['!statut'],                                                                                               staff: false },
  'suggestion.js':     { commands: ['!suggestion <texte>', '!configsuggestion #salon', '!acceptersugg <id>', '!rejetersugg <id>'],           staff: 'mixed' },
  'team_manage.js':    { commands: ['!fusionner <T1> <T2>', '!reinitjoueur <équipe> <nom>'],                                                 staff: true },
  'teaminfo.js':       { commands: ['!infoequipe <nom>'],                                                                                     staff: false },
  'ticket.js':         { commands: ['!ticket [type]', '!ticket panneau', '!tickets', '!prendre', '!resoudre', '!fermer', '!ajouteruser', '!retireruser', '!renommerticket', '!configticket'], staff: 'mixed' },
  'top.js':            { commands: ['!top [N]'],                                                                                              staff: false },
  'top3.js':           { commands: ['!top3 [30|saison]'],                                                                                    staff: false },
  'topactivite.js':    { commands: ['!topactivite [N]'],                                                                                      staff: false },
  'tournoiplus.js':    { commands: ['!vainqueurs', '!prochainmatch', '!annulermatch <id>', '!saisoncourante', '!classementsaison <nom>'],     staff: 'mixed' },
  'tournoidetail.js':  { commands: ['!detailtournoi <nom>'],                                                                                  staff: false },
  'tournois.js':       { commands: ['!tournois'],                                                                                             staff: false },
  'unregister.js':     { commands: ['!desenregistrer <nom>'],                                                                                 staff: true },
  'userinfo.js':       { commands: ['!infoutilisateur [@membre]'],                                                                            staff: false },
  'utilitairesplus.js':{ commands: ['!rebours <date> [événement]', '!tempsenligne', '!memoire', '!lienbot'],                                staff: 'mixed' },
  'voirconfig.js':     { commands: ['!voirconfig'],                                                                                           staff: true },
  'waitlist.js':       { commands: ['!listedattente', '!listedattente configurer|initialiser|liste|confirmer|retirer|vip|places|réinitialiser|infos'], staff: 'mixed' },
  'warn.js':           { commands: ['!avertir @membre <raison>', '!avertissements @membre', '!supprimerwarn <id>'],                          staff: 'mixed' },
  'welcome.js':        { commands: ['!bienvenue definir|salon|tester|activer|desactiver'],                                                    staff: true },
  'xpmanage.js':       { commands: ['!progression [@membre]', '!donnerxp @membre <qté>', '!retirerxp @membre <qté>', '!niveau reinitialiser @membre'], staff: 'mixed' },
  'xpmulti.js':        { commands: ['!xp multiplicateur #salon <val>', '!xp multiplicateurs'],                                               staff: true },
  // --- Nouvelles commandes v2 ---
  'elo.js':            { commands: ['!elo <équipe>', '!classementelo'],                                                                       staff: false },
  'statsserveur.js':   { commands: ['!statsserveur'],                                                                                         staff: false },
  'draft.js':          { commands: ['!draftequipe [N]'],                                                                                      staff: true },
  'badge.js':          { commands: ['!badge donner|retirer|liste', '!badges'],                                                                staff: 'mixed' },
  'record.js':         { commands: ['!record <équipe>', '!record joueur <nom>'],                                                              staff: false },
  'rivaux.js':         { commands: ['!rivaux <équipe>'],                                                                                      staff: false },
  'teamvoice.js':      { commands: ['!voixequipe <équipe>', '!voixequipe supprimer <équipe>'],                                                  staff: true },
  'auditactivite.js':  { commands: ['!auditactivite [N]'],                                                                                    staff: true },
  'mvpmatch.js':       { commands: ['!mvpmatch <id> <joueur>', '!mvpmatch liste', '!mvpmatch joueur <nom>'],                                  staff: 'mixed' },
  'capitaines.js':     { commands: ['!capitaines'],                                                                                           staff: false },
  'matchplan.js':      { commands: ['!planifiermatch', '!rappelsmatch'],                                                                      staff: 'mixed' },
};
